// Dữ liệu học: [cụm từ, nghĩa tiếng Việt, câu ví dụ]
const PHRASES = {
  A1: [
    ["Good morning", "Chào buổi sáng", "Good morning, how are you today?"],
    ["Nice to meet you", "Rất vui được gặp bạn", "Hi, I'm Anna. Nice to meet you."],
    ["How are you?", "Bạn khỏe không?", "Hello Tom, how are you?"],
    ["I'm fine, thank you", "Tôi khỏe, cảm ơn", "I'm fine, thank you. And you?"],
    ["What's your name?", "Bạn tên là gì?", "Excuse me, what's your name?"],
    ["Where are you from?", "Bạn đến từ đâu?", "Where are you from? I'm from Vietnam."],
    ["I live in", "Tôi sống ở", "I live in Hanoi with my family."],
    ["See you later", "Hẹn gặp lại", "I have to go now. See you later!"],
    ["Excuse me", "Xin lỗi (làm phiền)", "Excuse me, where is the bus stop?"],
    ["I'm sorry", "Tôi xin lỗi", "I'm sorry, I'm late."],
    ["Thank you very much", "Cảm ơn rất nhiều", "Thank you very much for your help."],
    ["You're welcome", "Không có gì", "Thanks! – You're welcome."],
    ["How old are you?", "Bạn bao nhiêu tuổi?", "How old are you? I'm twenty-five."],
    ["What time is it?", "Mấy giờ rồi?", "What time is it? It's seven o'clock."],
    ["I like", "Tôi thích", "I like coffee and music."],
    ["I don't like", "Tôi không thích", "I don't like rainy days."],
    ["get up", "thức dậy", "I get up at six every morning."],
    ["have breakfast", "ăn sáng", "We have breakfast at seven."],
    ["go to work", "đi làm", "My father goes to work by bus."],
    ["go to school", "đi học", "The children go to school on foot."],
    ["go home", "về nhà", "I go home at five thirty."],
    ["go to bed", "đi ngủ", "I usually go to bed at eleven."],
    ["take a shower", "tắm (vòi sen)", "I take a shower after work."],
    ["watch TV", "xem TV", "We watch TV in the evening."],
    ["listen to music", "nghe nhạc", "She listens to music on the bus."],
    ["play football", "chơi bóng đá", "They play football on Sundays."],
    ["How much is it?", "Cái này bao nhiêu tiền?", "I like this shirt. How much is it?"],
    ["Can I have...?", "Cho tôi... được không?", "Can I have a glass of water, please?"],
    ["I'd like", "Tôi muốn (lịch sự)", "I'd like a cup of tea, please."],
    ["the bill, please", "làm ơn tính tiền", "Excuse me, the bill, please."],
    ["on the left", "bên trái", "The bank is on the left."],
    ["on the right", "bên phải", "Turn right. The station is on the right."],
    ["next to", "bên cạnh", "The café is next to the bookshop."],
    ["in front of", "phía trước", "I'll wait in front of the cinema."],
    ["at home", "ở nhà", "I'm at home now."],
    ["every day", "mỗi ngày", "I study English every day."],
    ["at the weekend", "vào cuối tuần", "What do you do at the weekend?"],
    ["a lot of", "nhiều", "There are a lot of people here."],
    ["I don't understand", "Tôi không hiểu", "Sorry, I don't understand. Can you repeat?"],
    ["Can you repeat, please?", "Bạn nhắc lại được không?", "Can you repeat, please? Slowly."],
    ["speak slowly", "nói chậm", "Please speak slowly."],
    ["my favourite", "yêu thích nhất của tôi", "Blue is my favourite colour."],
    ["I have got", "Tôi có", "I have got two brothers."],
    ["There is / There are", "Có (tồn tại)", "There is a park near my house."],
    ["be hungry", "đói", "I'm hungry. Let's eat."],
    ["be thirsty", "khát", "Are you thirsty? Here's some water."],
    ["be tired", "mệt", "I'm tired after work."],
    ["Happy birthday", "Chúc mừng sinh nhật", "Happy birthday, Linh!"],
    ["Let's go", "Đi thôi", "Let's go to the park."],
    ["What do you do?", "Bạn làm nghề gì?", "What do you do? I'm a teacher."],
    ["cook dinner", "nấu bữa tối", "My mother cooks dinner every day."],
    ["do homework", "làm bài tập về nhà", "I do my homework after school."],
    ["wash the dishes", "rửa bát", "I wash the dishes after dinner."],
    ["by bus", "bằng xe buýt", "I go to the city by bus."],
    ["It's cold", "Trời lạnh", "It's cold today. Wear a coat."],
    ["It's hot", "Trời nóng", "It's very hot in summer."],
    ["Have a nice day", "Chúc một ngày tốt lành", "Goodbye and have a nice day!"],
    ["Me too", "Tôi cũng vậy", "I love pizza. – Me too!"],
    ["Of course", "Tất nhiên", "Can I sit here? – Of course."],
    ["No problem", "Không vấn đề gì", "Sorry for the wait. – No problem."]
  ],
  A2: [
    ["look for", "tìm kiếm", "I'm looking for my keys."],
    ["look after", "chăm sóc", "She looks after her little brother."],
    ["wait for", "chờ đợi", "I'm waiting for the bus."],
    ["get on / get off", "lên / xuống (xe)", "Get off the bus at the next stop."],
    ["turn on / turn off", "bật / tắt", "Please turn off the lights."],
    ["put on", "mặc vào", "Put on your jacket. It's cold."],
    ["take off", "cởi ra; cất cánh", "Take off your shoes, please."],
    ["pick up", "nhặt lên; đón", "I'll pick you up at eight."],
    ["try on", "mặc thử", "Can I try on these jeans?"],
    ["be good at", "giỏi về", "He's good at maths."],
    ["be interested in", "quan tâm đến", "I'm interested in history."],
    ["be afraid of", "sợ", "My sister is afraid of dogs."],
    ["be bored", "chán", "I was bored, so I read a book."],
    ["make a mistake", "mắc lỗi", "Don't worry if you make a mistake."],
    ["make friends", "kết bạn", "It's easy to make friends at school."],
    ["make a phone call", "gọi điện", "I need to make a phone call."],
    ["do the shopping", "đi mua sắm (đồ dùng)", "I do the shopping on Saturday."],
    ["have a good time", "có khoảng thời gian vui vẻ", "We had a good time at the party."],
    ["have a look", "xem qua", "Can I have a look at your photos?"],
    ["take a photo", "chụp ảnh", "Can you take a photo of us?"],
    ["take a break", "nghỉ giải lao", "Let's take a break for ten minutes."],
    ["catch a cold", "bị cảm", "I caught a cold last week."],
    ["feel better", "cảm thấy khá hơn", "I hope you feel better soon."],
    ["What's the matter?", "Có chuyện gì vậy?", "You look sad. What's the matter?"],
    ["I've got a headache", "Tôi bị đau đầu", "I've got a headache. I need to rest."],
    ["How was your weekend?", "Cuối tuần của bạn thế nào?", "How was your weekend? – Great!"],
    ["last year", "năm ngoái", "I visited Da Nang last year."],
    ["a long time ago", "lâu rồi", "I met him a long time ago."],
    ["in the future", "trong tương lai", "In the future, I want to live abroad."],
    ["I'm going to", "Tôi sẽ (dự định)", "I'm going to learn to drive."],
    ["Would you like...?", "Bạn có muốn...?", "Would you like some coffee?"],
    ["What about...?", "Còn... thì sao?", "What about going to the cinema?"],
    ["Why don't we...?", "Sao chúng ta không...?", "Why don't we eat out tonight?"],
    ["That sounds great", "Nghe tuyệt đấy", "A picnic? That sounds great!"],
    ["I'm afraid I can't", "Tôi e là không thể", "I'm afraid I can't come tomorrow."],
    ["Could you help me?", "Bạn giúp tôi được không?", "Could you help me with this bag?"],
    ["How do I get to...?", "Làm sao để đến...?", "How do I get to the train station?"],
    ["go straight on", "đi thẳng", "Go straight on and turn left."],
    ["It takes (time)", "Mất (thời gian)", "It takes 20 minutes to get there."],
    ["book a room", "đặt phòng", "I'd like to book a room for two nights."],
    ["check in / check out", "nhận / trả phòng", "What time do we check out?"],
    ["on holiday", "đi nghỉ", "We're on holiday in Nha Trang."],
    ["spend money", "tiêu tiền", "I spend too much money on clothes."],
    ["save money", "tiết kiệm tiền", "I'm saving money for a new phone."],
    ["on sale", "đang giảm giá", "These shoes are on sale."],
    ["It depends", "Còn tùy", "Do you go out at night? – It depends."],
    ["as soon as possible", "càng sớm càng tốt", "Please call me as soon as possible."],
    ["for example", "ví dụ", "I like sports, for example tennis."],
    ["at the moment", "hiện tại", "I'm busy at the moment."],
    ["once a week", "một lần mỗi tuần", "I go swimming once a week."],
    ["get married", "kết hôn", "They got married in 2020."],
    ["get a job", "kiếm được việc", "He got a job at a bank."],
    ["get lost", "bị lạc", "We got lost in the old town."],
    ["get ready", "chuẩn bị sẵn sàng", "Get ready! We leave in five minutes."],
    ["be in a hurry", "đang vội", "Sorry, I'm in a hurry."],
    ["keep in touch", "giữ liên lạc", "Let's keep in touch after the course."],
    ["It doesn't matter", "Không sao đâu", "I forgot your pen. – It doesn't matter."],
    ["I agree", "Tôi đồng ý", "I agree with you."],
    ["in my opinion", "theo ý kiến của tôi", "In my opinion, the film was boring."],
    ["Never mind", "Đừng bận tâm", "Never mind, we can try again."]
  ],
  B1: [
    ["get along with", "hòa hợp với", "I get along well with my colleagues."],
    ["give up", "từ bỏ", "Don't give up. You can do it!"],
    ["find out", "tìm ra, phát hiện", "I found out the truth yesterday."],
    ["come up with", "nghĩ ra (ý tưởng)", "She came up with a great idea."],
    ["run out of", "hết (cái gì)", "We've run out of milk."],
    ["look forward to", "mong chờ", "I look forward to hearing from you."],
    ["put off", "trì hoãn", "Stop putting off your homework."],
    ["set up", "thành lập, thiết lập", "They set up a small business."],
    ["take care of", "chăm sóc, lo liệu", "I'll take care of the tickets."],
    ["deal with", "giải quyết", "How do you deal with stress?"],
    ["carry on", "tiếp tục", "Carry on, I'm listening."],
    ["turn down", "từ chối; vặn nhỏ", "He turned down the job offer."],
    ["make up your mind", "quyết định", "Have you made up your mind yet?"],
    ["make sure", "đảm bảo", "Make sure you lock the door."],
    ["make progress", "tiến bộ", "You're making good progress in English."],
    ["make a decision", "đưa ra quyết định", "It's hard to make a decision."],
    ["take part in", "tham gia", "I took part in a marathon."],
    ["take advantage of", "tận dụng", "Take advantage of the free lessons."],
    ["pay attention to", "chú ý đến", "Pay attention to the details."],
    ["have an impact on", "có ảnh hưởng đến", "Social media has an impact on young people."],
    ["be used to", "quen với", "I'm used to getting up early."],
    ["be supposed to", "được cho là phải", "We're supposed to finish by Friday."],
    ["be responsible for", "chịu trách nhiệm", "She is responsible for marketing."],
    ["be aware of", "nhận thức được", "Are you aware of the risks?"],
    ["be likely to", "có khả năng", "It's likely to rain tonight."],
    ["on the other hand", "mặt khác", "The city is exciting. On the other hand, it's expensive."],
    ["as a result", "kết quả là", "He studied hard. As a result, he passed."],
    ["in addition", "thêm vào đó", "In addition, the hotel has a pool."],
    ["however", "tuy nhiên", "It was cheap. However, it broke quickly."],
    ["although", "mặc dù", "Although it was late, we kept working."],
    ["in spite of", "bất chấp", "In spite of the rain, we went out."],
    ["as long as", "miễn là", "You can go as long as you're back by ten."],
    ["unless", "trừ khi", "I won't go unless you come with me."],
    ["I'd rather", "Tôi thà / muốn... hơn", "I'd rather stay home tonight."],
    ["It's worth", "Đáng để", "This book is worth reading."],
    ["I can't stand", "Tôi không chịu nổi", "I can't stand waiting in queues."],
    ["I'm into", "Tôi rất thích", "I'm really into photography."],
    ["to be honest", "thành thật mà nói", "To be honest, I didn't like it."],
    ["as far as I know", "theo như tôi biết", "As far as I know, the shop is closed."],
    ["It's up to you", "Tùy bạn", "Pizza or sushi? It's up to you."],
    ["in the long run", "về lâu dài", "Exercise saves money in the long run."],
    ["from time to time", "thỉnh thoảng", "I visit my grandparents from time to time."],
    ["by the way", "nhân tiện", "By the way, did you call Mai?"],
    ["on time", "đúng giờ", "The train arrived on time."],
    ["in time", "kịp lúc", "We got there just in time."],
    ["work out", "tập thể dục; giải quyết", "I work out three times a week."],
    ["catch up with", "bắt kịp; gặp lại trò chuyện", "Let's catch up with each other soon."],
    ["keep up with", "theo kịp", "It's hard to keep up with new technology."],
    ["break down", "hỏng (máy)", "My car broke down on the highway."],
    ["apply for", "nộp đơn xin", "I'm applying for a new job."],
    ["earn a living", "kiếm sống", "He earns a living as a designer."],
    ["meet a deadline", "kịp hạn chót", "We worked late to meet the deadline."],
    ["raise awareness", "nâng cao nhận thức", "The campaign raises awareness of pollution."],
    ["save time", "tiết kiệm thời gian", "Online shopping saves time."],
    ["waste time", "lãng phí thời gian", "Don't waste time on your phone."],
    ["Would you mind...?", "Bạn có phiền...?", "Would you mind opening the window?"],
    ["I was wondering if", "Tôi đang tự hỏi liệu", "I was wondering if you could help me."],
    ["That makes sense", "Điều đó hợp lý", "Oh, I see. That makes sense."],
    ["I see your point, but", "Tôi hiểu ý bạn, nhưng", "I see your point, but I disagree."],
    ["No wonder", "Chẳng trách", "You didn't sleep? No wonder you're tired."]
  ],
  B2: [
    ["bring about", "gây ra, mang lại", "The internet brought about huge changes."],
    ["account for", "chiếm; giải thích cho", "Young people account for 40% of users."],
    ["cut down on", "cắt giảm", "I'm trying to cut down on sugar."],
    ["get over", "vượt qua (khó khăn, bệnh)", "It took her months to get over the break-up."],
    ["live up to", "đáp ứng (kỳ vọng)", "The film didn't live up to expectations."],
    ["put up with", "chịu đựng", "I can't put up with the noise anymore."],
    ["rule out", "loại trừ", "We can't rule out the possibility."],
    ["stand out", "nổi bật", "Her CV really stands out."],
    ["point out", "chỉ ra", "He pointed out a mistake in the report."],
    ["figure out", "hiểu ra, tìm cách", "I can't figure out how this works."],
    ["come across", "tình cờ gặp; tạo ấn tượng", "I came across an old photo."],
    ["take into account", "tính đến, xem xét", "We must take costs into account."],
    ["play a key role in", "đóng vai trò then chốt", "Education plays a key role in development."],
    ["have a point", "nói có lý", "You have a point there."],
    ["draw a conclusion", "rút ra kết luận", "It's too early to draw a conclusion."],
    ["reach an agreement", "đạt được thỏa thuận", "The two sides reached an agreement."],
    ["meet the needs of", "đáp ứng nhu cầu", "The service meets the needs of elderly people."],
    ["pose a threat to", "gây ra mối đe dọa", "Plastic poses a threat to marine life."],
    ["tackle a problem", "giải quyết vấn đề", "The government must tackle unemployment."],
    ["a wide range of", "nhiều loại", "The shop offers a wide range of products."],
    ["to a large extent", "ở mức độ lớn", "To a large extent, I agree."],
    ["in terms of", "xét về mặt", "In terms of price, it's the best option."],
    ["with regard to", "liên quan đến", "With regard to your question, ..."],
    ["as opposed to", "trái ngược với", "I prefer trains, as opposed to planes."],
    ["by no means", "hoàn toàn không", "It is by no means easy."],
    ["nevertheless", "tuy vậy", "It was risky. Nevertheless, they did it."],
    ["whereas", "trong khi (đối lập)", "I love cities, whereas my wife prefers the countryside."],
    ["provided that", "với điều kiện là", "You can borrow it provided that you return it."],
    ["it goes without saying", "khỏi phải nói", "It goes without saying that safety comes first."],
    ["there's no doubt that", "không nghi ngờ gì", "There's no doubt that climate change is real."],
    ["it's widely believed that", "nhiều người tin rằng", "It's widely believed that reading improves empathy."],
    ["on the whole", "nhìn chung", "On the whole, the trip was a success."],
    ["at the end of the day", "suy cho cùng", "At the end of the day, it's your choice."],
    ["the bottom line is", "điều cốt lõi là", "The bottom line is we need more money."],
    ["a piece of cake", "dễ như ăn bánh", "The exam was a piece of cake."],
    ["break the ice", "phá vỡ sự ngại ngùng", "He told a joke to break the ice."],
    ["hit the nail on the head", "nói trúng vấn đề", "You've hit the nail on the head."],
    ["get the hang of", "nắm được cách làm", "You'll get the hang of it soon."],
    ["on the verge of", "trên bờ vực", "The company is on the verge of collapse."],
    ["keep an eye on", "để mắt đến", "Can you keep an eye on my bag?"],
    ["be keen on", "hứng thú với", "I'm not keen on horror films."],
    ["be prone to", "dễ bị", "He's prone to making careless mistakes."],
    ["be entitled to", "có quyền", "Employees are entitled to paid leave."],
    ["be committed to", "cam kết, tận tâm", "We are committed to quality."],
    ["hold a meeting", "tổ chức cuộc họp", "We'll hold a meeting on Monday."],
    ["run a business", "điều hành kinh doanh", "She runs a business from home."],
    ["gain experience", "tích lũy kinh nghiệm", "Internships help you gain experience."],
    ["broaden your horizons", "mở rộng tầm nhìn", "Travelling broadens your horizons."],
    ["strike a balance", "cân bằng", "It's hard to strike a balance between work and life."],
    ["take something for granted", "coi là hiển nhiên", "Don't take your health for granted."],
    ["come to terms with", "chấp nhận (điều khó khăn)", "He came to terms with his loss."],
    ["make the most of", "tận dụng tối đa", "Make the most of your time abroad."],
    ["jump to conclusions", "vội kết luận", "Don't jump to conclusions."],
    ["keep something in mind", "ghi nhớ điều gì", "Keep in mind that the shop closes early."],
    ["let alone", "huống chi", "I can't cook rice, let alone a full meal."],
    ["for the time being", "tạm thời", "I'm staying here for the time being."],
    ["all things considered", "cân nhắc mọi thứ", "All things considered, it was a good decision."],
    ["it's high time", "đã đến lúc", "It's high time we changed our habits."],
    ["no matter how", "dù thế nào đi nữa", "No matter how hard it is, keep going."],
    ["out of the question", "không thể được", "Going out tonight is out of the question."]
  ]
};

const READINGS = {
  A1: [
    { title: "My Day", text: "My name is Lan. I am 24 years old. I live in Hanoi. I get up at six o'clock every morning. I have breakfast with my mother. Then I go to work by bus. I work in a small shop. I finish work at five. In the evening, I cook dinner and watch TV. I go to bed at eleven.",
      qs: [["Where does Lan live?", ["Da Nang", "Hanoi", "Hue"], 1], ["How does she go to work?", ["By bus", "By car", "On foot"], 0], ["When does she go to bed?", ["At ten", "At six", "At eleven"], 2]] },
    { title: "At the Café", text: "Tom goes to a café on Sunday. It is next to the park. He likes the café because it is quiet. He orders a cup of coffee and a sandwich. The coffee is two dollars and the sandwich is four dollars. Tom reads a book there for two hours.",
      qs: [["Where is the café?", ["Next to the park", "Next to the bank", "In front of the school"], 0], ["How much is the sandwich?", ["Two dollars", "Four dollars", "Six dollars"], 1], ["What does Tom do there?", ["He sleeps", "He works", "He reads"], 2]] }
  ],
  A2: [
    { title: "A Weekend Trip", text: "Last weekend, Minh and his friends went to Ha Long Bay. They left Hanoi early on Saturday morning and it took about three hours by bus. The weather was sunny and warm. They took a boat trip and visited a big cave. In the evening they ate seafood in a small restaurant. Minh took a lot of photos. On Sunday it rained, so they stayed in the hotel and played cards. They had a really good time.",
      qs: [["How long was the bus journey?", ["One hour", "About three hours", "Five hours"], 1], ["What did they eat in the evening?", ["Pizza", "Seafood", "Noodles"], 1], ["Why did they stay in the hotel on Sunday?", ["They were tired", "It rained", "The boat was closed"], 1]] },
    { title: "A New Job", text: "Sara is looking for a new job. She is good at languages and she is interested in travel, so she wants to work in a hotel. Yesterday she had an interview. She was nervous, but the manager was friendly. He asked her about her experience. Sara is going to start next Monday. She is very happy because the hotel is near her home.",
      qs: [["Where does Sara want to work?", ["In a school", "In a hotel", "In a bank"], 1], ["How did she feel in the interview?", ["Nervous", "Bored", "Angry"], 0], ["Why is she happy?", ["The pay is high", "The hotel is near her home", "She can travel abroad"], 1]] }
  ],
  B1: [
    { title: "Working from Home", text: "Since 2020, many companies have allowed employees to work from home. Supporters say it saves time because people don't have to commute, and it helps them strike a better balance between work and family. However, not everyone agrees. Some workers feel lonely and find it hard to separate their private life from their job. Managers also worry that teamwork suffers when people rarely meet. As a result, many companies now use a 'hybrid' model: staff work at the office two or three days a week and at home for the rest.",
      qs: [["What is one advantage of working from home?", ["Higher salary", "No commuting", "More meetings"], 1], ["What problem do some workers have?", ["They feel lonely", "They earn less", "They travel more"], 0], ["What is the 'hybrid' model?", ["Working only at home", "Working only at the office", "A mix of office and home"], 2]] },
    { title: "Learning a Language", text: "Many people give up learning a language after a few months. Experts say the main reason is that learners expect quick results. In fact, making progress takes time and regular practice. It is better to study for twenty minutes every day than for three hours once a week. Learners should also pay attention to listening and speaking, not only grammar. Watching films with subtitles, talking to native speakers online and reviewing new words regularly are all effective methods.",
      qs: [["Why do many learners give up?", ["Lessons are expensive", "They expect quick results", "Grammar is too hard"], 1], ["What do experts recommend?", ["Study a little every day", "Study only at weekends", "Study only grammar"], 0], ["Which is NOT mentioned as a method?", ["Watching films", "Talking online", "Writing poems"], 2]] }
  ],
  B2: [
    { title: "The Price of Fast Fashion", text: "Fast fashion has transformed the way we shop. Clothes are produced quickly and cheaply, allowing consumers to follow trends at a fraction of the cost of a few decades ago. Nevertheless, this convenience comes at a price. The industry accounts for a significant share of global carbon emissions and uses enormous quantities of water. In addition, workers in some producing countries are paid extremely low wages. Critics argue that consumers take cheap clothing for granted and rarely consider its true cost. Some brands have responded by launching recycling schemes, but sceptics claim these initiatives are largely marketing. Ultimately, tackling the problem may require both stricter regulation and a shift in consumer attitudes.",
      qs: [["What is the main advantage of fast fashion for consumers?", ["Better quality", "Low prices and following trends", "Fair wages"], 1], ["What do sceptics think about recycling schemes?", ["They are very effective", "They are mostly marketing", "They are too expensive"], 1], ["According to the text, what may be needed?", ["Only new technology", "Regulation and changes in attitudes", "Higher taxes on cotton"], 1]] },
    { title: "Sleep and Productivity", text: "In many workplaces, long hours are seen as a sign of commitment. Yet research consistently shows that lack of sleep has a detrimental impact on performance. People who sleep fewer than six hours a night are more prone to making errors, find it harder to concentrate and are less creative. Some forward-thinking companies have introduced nap rooms and flexible start times, recognising that well-rested employees are more productive in the long run. While such measures are by no means universal, they reflect a growing awareness that productivity is not simply a matter of the number of hours worked.",
      qs: [["What is the effect of sleeping less than six hours?", ["More creativity", "More errors", "Better concentration"], 1], ["What have some companies introduced?", ["Longer hours", "Nap rooms", "Weekend work"], 1], ["What is the main idea?", ["Productivity depends only on hours", "Rest improves productivity", "Nap rooms are universal"], 1]] }
  ]
};

const WRITING = {
  A1: ["Giới thiệu bản thân: tên, tuổi, nơi sống, sở thích (40-60 từ).", "Mô tả một ngày bình thường của bạn (40-60 từ).", "Mô tả gia đình bạn (40-60 từ).", "Viết về món ăn yêu thích của bạn (40-60 từ)."],
  A2: ["Kể về cuối tuần vừa rồi của bạn (dùng thì quá khứ, 60-80 từ).", "Viết email mời bạn đi xem phim (60-80 từ).", "Kế hoạch cho kỳ nghỉ tới (dùng 'going to', 60-80 từ).", "Mô tả thành phố của bạn (60-80 từ)."],
  B1: ["Ưu và nhược điểm của mạng xã hội (120-150 từ).", "Viết email xin việc bán thời gian (120-150 từ).", "Kể về một trải nghiệm đáng nhớ (120-150 từ).", "Nên học online hay học trên lớp? Nêu ý kiến (120-150 từ)."],
  B2: ["Essay: Chính phủ có nên đánh thuế đồ ăn nhanh? (200-250 từ)", "Essay: Công nghệ làm con người cô đơn hơn? (200-250 từ)", "Viết bài review một cuốn sách/phim (200-250 từ).", "Báo cáo: đề xuất cải thiện giao thông ở thành phố bạn (200-250 từ)."]
};

const GRAMMAR = {
  A1: [["Present simple", "I work / She works. Dùng cho thói quen, sự thật.", "She drinks coffee every morning."], ["To be", "I am, you/we/they are, he/she/it is.", "They are students."], ["Can / can't", "Khả năng: can + V nguyên mẫu.", "I can swim, but I can't dance."], ["There is / are", "Có: there is + số ít, there are + số nhiều.", "There are two cats in the garden."]],
  A2: [["Past simple", "V-ed hoặc bất quy tắc (went, saw). Hành động đã kết thúc.", "I visited my aunt yesterday."], ["Be going to", "Dự định tương lai.", "We are going to move house."], ["Comparatives", "Adj-er / more + adj + than.", "Hanoi is bigger than Hue."], ["Present continuous", "am/is/are + V-ing. Đang xảy ra.", "She is cooking now."]],
  B1: [["Present perfect", "have/has + V3. Kinh nghiệm, kết quả tới hiện tại.", "I have been to Japan twice."], ["First & second conditional", "If + hiện tại, will... / If + quá khứ, would...", "If I had more time, I would travel."], ["Passive voice", "be + V3.", "The bridge was built in 1902."], ["Relative clauses", "who, which, that, where.", "The man who lives next door is a doctor."]],
  B2: [["Third conditional", "If + had V3, would have V3.", "If I had studied, I would have passed."], ["Reported speech", "Lùi thì khi tường thuật.", "She said she was tired."], ["Inversion", "Never have I..., Not only... but also.", "Not only is it cheap, but it's also fast."], ["Wish / If only", "Tiếc nuối hiện tại/quá khứ.", "I wish I had listened to you."]]
};
