// Họ từ (word family): n = danh từ, v = động từ, adj = tính từ, adv = trạng từ
const FAMILY_RAW = `
morning:n:morning
nice:adj:nice|adv:nicely|n:niceness
meet:v:meet|n:meeting
fine:adj:fine|adv:finely
name:n:name|v:name|adj:nameless
live:v:live|adj:alive,lively,living|n:life,living
sorry:adj:sorry|n:sorrow|adj2:sorrowful
thank:v:thank|n:thanks|adj:thankful|adv:thankfully
welcome:v:welcome|n:welcome|adj:welcome
old:adj:old|n:age|v:age
like:v:like|n:liking|adj:likeable
breakfast:n:breakfast
work:v:work|n:work,worker|adj:working
school:n:school,schooling
home:n:home|adj:homeless|adv:home
bed:n:bed
shower:n:shower|v:shower
watch:v:watch|n:watch
listen:v:listen|n:listener
music:n:music,musician|adj:musical|adv:musically
play:v:play|n:play,player|adj:playful|adv:playfully
football:n:football
help:v:help|n:help,helper|adj:helpful,helpless|adv:helpfully
left:n:left|adj:left|adv:left
right:n:right|adj:right|adv:right,rightly
front:n:front|adj:front
day:n:day|adj:daily|adv:daily
weekend:n:weekend
understand:v:understand|n:understanding|adj:understandable,understanding
repeat:v:repeat|n:repetition|adj:repetitive,repeated|adv:repeatedly
speak:v:speak|n:speech,speaker|adj:spoken
slow:adj:slow|adv:slowly|v:slow|n:slowness
favourite:adj:favourite|n:favourite,favour
hungry:adj:hungry|n:hunger|adv:hungrily
thirsty:adj:thirsty|n:thirst
tired:adj:tired,tiring,tireless|v:tire|n:tiredness
happy:adj:happy|n:happiness|adv:happily
birthday:n:birthday|n2:birth
cook:v:cook|n:cook,cooker,cookery,cooking
dinner:n:dinner
homework:n:homework
wash:v:wash|n:wash,washing
dishes:n:dish
bus:n:bus
cold:adj:cold|n:cold|adv:coldly
hot:adj:hot|n:heat|v:heat|adv:hotly
problem:n:problem|adj:problematic
course:n:course
look:v:look|n:look
wait:v:wait|n:wait,waiter,waitress
good:adj:good|n:good,goodness|adv:well
interested:adj:interested,interesting|n:interest|v:interest|adv:interestingly
afraid:adj:afraid|n:fear|v:fear|adj2:fearful,fearless
bored:adj:bored,boring|v:bore|n:boredom
mistake:n:mistake|v:mistake|adj:mistaken|adv:mistakenly
friends:n:friend,friendship|adj:friendly,unfriendly|v:befriend
phone:n:phone|v:phone
shopping:n:shopping,shop,shopper|v:shop
photo:n:photo,photograph,photographer,photography|v:photograph|adj:photographic
break:v:break|n:break|adj:broken,breakable
feel:v:feel|n:feeling
better:adj:better|adv:better|v:better
headache:n:headache,ache|v:ache
future:n:future|adj:future
agree:v:agree|n:agreement|adj:agreeable|adv:agreeably
opinion:n:opinion|adj:opinionated
book:n:book|v:book|n2:booking
holiday:n:holiday
spend:v:spend|n:spending
save:v:save|n:saving,savings
sale:n:sale,seller|v:sell
depends:v:depend|n:dependence|adj:dependent,dependable
possible:adj:possible,impossible|n:possibility|adv:possibly
example:n:example|v:exemplify
moment:n:moment|adj:momentary|adv:momentarily
married:adj:married|v:marry|n:marriage
job:n:job|adj:jobless
lost:adj:lost|v:lose|n:loss,loser
ready:adj:ready|adv:readily|n:readiness
hurry:v:hurry|n:hurry|adj:hurried|adv:hurriedly
touch:v:touch|n:touch|adj:touching
matter:n:matter|v:matter
along:adv:along
forward:adv:forward|adj:forward
care:n:care|v:care|adj:careful,careless|adv:carefully,carelessly
deal:v:deal|n:deal,dealer
decision:n:decision|v:decide|adj:decisive|adv:decisively
sure:adj:sure|adv:surely|v:ensure
progress:n:progress|v:progress|adj:progressive|adv:progressively
part:n:part,participant,participation|v:participate|adj:partial|adv:partly
advantage:n:advantage,disadvantage|adj:advantageous
attention:n:attention|v:attend|adj:attentive|adv:attentively
impact:n:impact|v:impact
used:adj:used|v:use|n:use,user|adj2:useful,useless
supposed:adj:supposed|v:suppose|n:supposition|adv:supposedly
responsible:adj:responsible,irresponsible|n:responsibility|adv:responsibly
aware:adj:aware,unaware|n:awareness
likely:adj:likely,unlikely|n:likelihood
result:n:result|v:result|adj:resultant
addition:n:addition|v:add|adj:additional|adv:additionally
spite:n:spite|adj:spiteful
worth:adj:worth,worthy,worthwhile|n:worth
stand:v:stand|n:stand
honest:adj:honest,dishonest|n:honesty|adv:honestly
know:v:know|n:knowledge|adj:knowledgeable,known|adv:knowingly
time:n:time|v:time|adj:timely
apply:v:apply|n:application,applicant|adj:applicable
earn:v:earn|n:earnings
living:n:living|v:live|adj:living
deadline:n:deadline
awareness:n:awareness|adj:aware
waste:v:waste|n:waste|adj:wasteful|adv:wastefully
mind:n:mind|v:mind|adj:mindful
wondering:v:wonder|n:wonder|adj:wonderful|adv:wonderfully
sense:n:sense|adj:sensible,sensitive|adv:sensibly
point:n:point|v:point|adj:pointless
wonder:n:wonder|v:wonder|adj:wonderful|adv:wonderfully
account:n:account,accountant|v:account|adj:accountable
expectation:n:expectation|v:expect|adj:expected,unexpected|adv:unexpectedly
role:n:role
conclusion:n:conclusion|v:conclude|adj:conclusive|adv:conclusively
agreement:n:agreement|v:agree|adj:agreeable
needs:n:need|v:need|adj:needy,needless|adv:needlessly
threat:n:threat|v:threaten|adj:threatening
problem2:n:problem
range:n:range|v:range
extent:n:extent|v:extend|adj:extensive|adv:extensively
terms:n:term|v:term
regard:n:regard|v:regard|prep:regarding
opposed:adj:opposed,opposite|v:oppose|n:opposition,opponent
means:n:means|v:mean|n2:meaning|adj:meaningful,meaningless
doubt:n:doubt|v:doubt|adj:doubtful|adv:doubtfully,undoubtedly
believed:v:believe|n:belief,believer|adj:believable,unbelievable
widely:adv:widely|adj:wide|n:width|v:widen
whole:adj:whole|n:whole|adv:wholly
bottom:n:bottom|adj:bottom
cake:n:cake
ice:n:ice|adj:icy
nail:n:nail|v:nail
hang:v:hang|n:hang,hanger
verge:n:verge|v:verge
eye:n:eye|v:eye
keen:adj:keen|adv:keenly|n:keenness
prone:adj:prone
entitled:adj:entitled|v:entitle|n:entitlement
committed:adj:committed|v:commit|n:commitment,committee
meeting:n:meeting|v:meet
business:n:business,businessman|adj:busy
experience:n:experience|v:experience|adj:experienced,inexperienced
horizons:n:horizon|adj:horizontal|adv:horizontally
balance:n:balance|v:balance|adj:balanced
granted:v:grant|n:grant|adv:admittedly
terms2:n:term
most:adj:most|adv:most,mostly
conclusions:n:conclusion|v:conclude|adj:conclusive
considered:v:consider|n:consideration|adj:considerate,considerable|adv:considerably
high:adj:high|adv:high,highly|n:height|v:heighten
matter2:n:matter
question:n:question|v:question|adj:questionable
change:n:change|v:change|adj:changeable
threaten:v:threaten|n:threat
tackle:v:tackle|n:tackle
bring:v:bring
awaken:v:awaken
effect:n:effect|v:affect|adj:effective|adv:effectively
progress2:n:progress
`;
const FAMILY = {};
FAMILY_RAW.trim().split("\n").forEach(line => {
  const [word, ...rest] = line.split(":");
  const parts = line.slice(word.length + 1).split("|");
  const f = {};
  parts.forEach(p => { const [pos, words] = p.split(":"); const k = pos.replace(/\d$/, ""); f[k] = (f[k] ? f[k] + ", " : "") + words.replace(/,/g, ", "); });
  if (!/\d$/.test(word)) FAMILY[word] = f;
});
// Tra ngược: mọi dạng từ đều trỏ về cùng họ từ (decide → decision...)
Object.values(FAMILY).forEach(f => Object.values(f).join(", ").split(", ").forEach(w => { if (!FAMILY[w]) FAMILY[w] = f; }));
